//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_solicitudes.wcfDatos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfDatos.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarUsuario", ReplyAction="http://tempuri.org/IService/ValidarUsuarioResponse")]
        System.Data.DataSet ValidarUsuario(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ValidarUsuario", ReplyAction="http://tempuri.org/IService/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ValidarUsuarioAsync(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AgregarSolicitud", ReplyAction="http://tempuri.org/IService/AgregarSolicitudResponse")]
        System.Data.DataSet AgregarSolicitud(int ID_USUARIO, string ESTADO, string MOTIVO, string TIPO_FALTA, string TIEMPO_ESTIMADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AgregarSolicitud", ReplyAction="http://tempuri.org/IService/AgregarSolicitudResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> AgregarSolicitudAsync(int ID_USUARIO, string ESTADO, string MOTIVO, string TIPO_FALTA, string TIEMPO_ESTIMADO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ControlAsistencia", ReplyAction="http://tempuri.org/IService/ControlAsistenciaResponse")]
        System.Data.DataSet ControlAsistencia(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_ENTRA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ControlAsistencia", ReplyAction="http://tempuri.org/IService/ControlAsistenciaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ControlAsistenciaAsync(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_ENTRA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ControlAsistenciaSalir", ReplyAction="http://tempuri.org/IService/ControlAsistenciaSalirResponse")]
        System.Data.DataSet ControlAsistenciaSalir(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_SALIDA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ControlAsistenciaSalir", ReplyAction="http://tempuri.org/IService/ControlAsistenciaSalirResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ControlAsistenciaSalirAsync(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_SALIDA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DatosTb", ReplyAction="http://tempuri.org/IService/DatosTbResponse")]
        System.Data.DataSet DatosTb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DatosTb", ReplyAction="http://tempuri.org/IService/DatosTbResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> DatosTbAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : proyecto_solicitudes.wcfDatos.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<proyecto_solicitudes.wcfDatos.IService>, proyecto_solicitudes.wcfDatos.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ValidarUsuario(string Login, string Password) {
            return base.Channel.ValidarUsuario(Login, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ValidarUsuarioAsync(string Login, string Password) {
            return base.Channel.ValidarUsuarioAsync(Login, Password);
        }
        
        public System.Data.DataSet AgregarSolicitud(int ID_USUARIO, string ESTADO, string MOTIVO, string TIPO_FALTA, string TIEMPO_ESTIMADO) {
            return base.Channel.AgregarSolicitud(ID_USUARIO, ESTADO, MOTIVO, TIPO_FALTA, TIEMPO_ESTIMADO);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> AgregarSolicitudAsync(int ID_USUARIO, string ESTADO, string MOTIVO, string TIPO_FALTA, string TIEMPO_ESTIMADO) {
            return base.Channel.AgregarSolicitudAsync(ID_USUARIO, ESTADO, MOTIVO, TIPO_FALTA, TIEMPO_ESTIMADO);
        }
        
        public System.Data.DataSet ControlAsistencia(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_ENTRA) {
            return base.Channel.ControlAsistencia(ID_USUARIO, FECHA_MARCA, HORA_ENTRA);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ControlAsistenciaAsync(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_ENTRA) {
            return base.Channel.ControlAsistenciaAsync(ID_USUARIO, FECHA_MARCA, HORA_ENTRA);
        }
        
        public System.Data.DataSet ControlAsistenciaSalir(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_SALIDA) {
            return base.Channel.ControlAsistenciaSalir(ID_USUARIO, FECHA_MARCA, HORA_SALIDA);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ControlAsistenciaSalirAsync(int ID_USUARIO, System.DateTime FECHA_MARCA, System.DateTime HORA_SALIDA) {
            return base.Channel.ControlAsistenciaSalirAsync(ID_USUARIO, FECHA_MARCA, HORA_SALIDA);
        }
        
        public System.Data.DataSet DatosTb() {
            return base.Channel.DatosTb();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DatosTbAsync() {
            return base.Channel.DatosTbAsync();
        }
    }
}
